### ISSUE TITLE
USER STORY: Customized pizza order

### ISSUE THREAD

**Issue by CryptikEd** [CryptikEd/Eds-pizzahouse#3]
As a **restaurant guest** I can **see the menu** so that **i can customize my pizza**

## Acceptance Criteria

- [ ] Menu of available styles of pizza
- [ ] Customizable toppings menu

## Tasks

- [ ] Create a menu of three styles of pizza; Italian, New York and Deep Dish
- [ ] Create option list of 6 different toppings for each style
